apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  serviceAccount: jenkins
  volumes:
    - name: docker-credentials
      projected:
        sources:
          - secret:
              name: jenkins-dockercfg-rjj6m
              items:
                - key: .dockercfg
                  path: config.json
  containers:
    - name: origin
      image: openshift/origin-cli
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      env:
        - name: PATH
          value: "$PATH:/busybox:/kaniko"
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      tty: true
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: docker-credentials
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2048Mi"