kind: Template
apiVersion: v1
metadata:
  name: calculadora-db
  description: "Template to deploy Piloto #3 Database"
  tags: ibmcom/db2
labels:
  template: calculadora-db
  version: "1.0"
  component: "database"
  app: "${APP}"
parameters:
  - description: Application deployment name
    displayName: Application
    required: true
    name: APP
    value: 'calculadora'
  - description: 'The base name assigned to all of the objects defined in this template.'
    displayName: Name
    required: true
    name: NAME
    value: db
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: piloto3
  - description: The ImageStream name
    displayName: ImageStream
    name: IMAGE
    required: true
    value: db
  - description: Service Account with db2oltp-dev-scc configured
    displayName: Service Account 
    name: SA
    required: true
    value: db2sa
  - description: Database password
    displayName: Password
    name: PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{12}"
  - description: Database name
    displayName: DB Name
    name: DB_NAME
    required: true
    value: TEST
objects:
  - kind: Secret
    apiVersion: v1
    metadata: 
      name: ${APP}-${NAME}
      annotations:
        template.openshift.io/base64-expose-password: "{.data['password']}"
    stringData:
      password: ${PASSWORD}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
      annotations:
    data:
      dbname: ${DB_NAME}
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    spec:
      replicas: 1
      selector:
        template: calculadora-db
        version: "1.0"
        app: ${APP}
      template:
        metadata:
          labels:
            template: calculadora-db
            version: "1.0"
            app: ${APP}
        spec:
          serviceAccount: ${SA}
          hostNetwork: false
          hostPID: false
          hostIPC: true
          initContainers:
            - name: init-db2
              image: " "
              imagePullPolicy: "Always"
              command:
                - sh
                - -c
                - '/var/db2_setup/lib/set_kernel_params.sh'
              volumeMounts:
                - name: proc
                  mountPath: /host/proc
                  readOnly:  false
                - name: sys
                  mountPath: /host/proc/sys
                  readOnly: false
          containers:
            - name: db2
              image: " "
              imagePullPolicy: "Always"
              ports:
                - containerPort: 22
                  protocol: TCP
                - containerPort: 50000
                  protocol: TCP
                - containerPort: 55000
                  protocol: TCP
                - containerPort: 60006
                  protocol: TCP
                - containerPort: 60007
                  protocol: TCP
              env:
                - name: LICENSE 
                  value: accept
                - name: DBNAME
                  valueFrom:
                    configMapKeyRef:
                      name: ${APP}-${NAME}
                      key: dbname
                - name: DB2INST1_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${NAME}
                      key: password
                - name: DB2INSTANCE
                  value: db2inst1
              volumeMounts:
                - mountPath: /sys/fs/cgroup
                  name: cgvol
                  readOnly: true
                - mountPath: /database
                  name: db2-1
                - mountPath: /hadr
                  name: db2-2
              livenessProbe:
                exec:
                  command:
                  - sh
                  - -c
                  - su - $DB2INSTANCE  -c '/database/config/$DB2INSTANCE/sqllib/bin/db2gcf -s'
                initialDelaySeconds: 300
                periodSeconds: 90
                failureThreshold: 3
              readinessProbe:
                exec:
                  command:
                  - sh
                  - -c
                  - su - $DB2INSTANCE  -c '/database/config/$DB2INSTANCE/sqllib/bin/db2gcf -s'
                initialDelaySeconds: 300
                periodSeconds: 90
                failureThreshold: 3
              securityContext:
                privileged: true
          volumes:
            - name: db2-1
              persistentVolumeClaim: 
                claimName: ${APP}-${NAME}
            - name: db2-2
              emptyDir: {}
            - name: cgvol
              hostPath:
                path: /sys/fs/cgroup
            - name: sys
              hostPath:
                path: /proc/sys
            - name: proc
              hostPath:
                path: /proc
      triggers:
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - db2
              - init-db2
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}:latest
              namespace: ${NAMESPACE}
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    labels:
      app: ${APP}
    spec:
      selector:
        template: calculadora-db
        version: "1.0"
        app: ${APP}
      type: ClusterIP
      ports:
        - port: 22
          protocol: TCP
          name: 22-tcp
        - port: 50000
          protocol: TCP
          name: 50000-tcp
        - port: 55000
          protocol: TCP
          name: 55000-tcp
        - port: 60006
          protocol: TCP
          name: 60006-tcp
        - port: 60007
          protocol: TCP
          name: 60007-tcp